#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2025 STMicroelectronics.
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.

# =====================================================
# Imports
# =====================================================
import os
import sys
import base64
import hashlib
import secrets
import zipfile
import subprocess
import argparse
import configparser

# =====================================================
# Global variables
# =====================================================
USER_LABEL = "mqtt"
MQTT_USERNAME = "st67w6x"
MQTT_USER_PASSWORD = "12345678"
RED = "\033[1;31m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[1;34m"
PURPLE = "\033[1;35m"
CYAN = "\033[1;36m"
WHITE = "\033[1;37m"
NO_COLOR = "\033[0m"


# =====================================================
def run_openssl(command):
    try:
        print(f"{BLUE}Running command: {PURPLE}{command}{NO_COLOR}")
        subprocess.run(command, check=True, shell=True)
        print(f"{GREEN}Command executed successfully.{NO_COLOR}")
        print(" ")
    except subprocess.CalledProcessError as e:
        print(f"{RED}An error occurred: {e}{NO_COLOR}")
        sys.exit(0)


# =====================================================
def display_cert(cert_path):
    try:
        subprocess.run(f"openssl x509 -in {cert_path} -text -noout", check=True, shell=True)
        print(" ")
    except subprocess.CalledProcessError as e:
        print(f"{RED}An error occurred: {e}{NO_COLOR}")
        sys.exit(0)


# =====================================================
def load_common_name(config_path, fallback="server.local"):
    parser = configparser.ConfigParser()
    parser.read(config_path)

    if parser.has_option("req_distinguished_name", "commonName"):
        return parser.get("req_distinguished_name", "commonName")

    return fallback


# =====================================================
def pem_to_c_buffer(var_name, cert_path):
    with open(cert_path, "r", encoding="utf-8") as cert_file:
        lines = cert_file.read().splitlines()

    content = [f"static const char {var_name}[] ="]
    for line in lines:
        escaped_line = line.replace("\\", "\\\\").replace('"', '\\"')
        content.append(f"  \"{escaped_line}\\r\\n\"")
    # Append a semicolon on the last line of the array definition
    content[-1] += ";"  # Append semicolon to the last line
    return "\n".join(content)


# =====================================================
def generate_header_template(template_output_dir, label, sni, ca_cert_path, client_cert_path, client_key_path):
    cert_define = f"client_{label}.crt"
    key_define = f"client_{label}.key"
    ca_define = f"ca_{label}.crt"
    header_path = os.path.join(template_output_dir, "mqtt_certificate_template.h")

    header_content = [
        "/* Auto-generated by gen_mqtt_certificate.py",
        " * Content to be copied into MQTT application file.",
        " * To be used with a local MQTT broker such as Mosquitto with TLS support.",
        " */",
        "#ifndef MQTT_CERTIFICATE_TEMPLATE_H",
        "#define MQTT_CERTIFICATE_TEMPLATE_H",
        "",
        "#define MQTT_SECURITY_LEVEL             4",
        "",
        "#if (MQTT_SECURITY_LEVEL == 0)",
        "#define MQTT_HOST_PORT                  1883",
        "#else",
        "#define MQTT_HOST_PORT                  8883",
        "#endif /* MQTT_SECURITY_LEVEL */",
        "",
        "#if ((MQTT_SECURITY_LEVEL == 0) || (MQTT_SECURITY_LEVEL == 1))",
        "#define MQTT_SNI                        \"\"",
        "#else",
        f"#define MQTT_SNI                        \"{sni}\"",
        "#endif /* MQTT_SECURITY_LEVEL */",
        "",
        f"#define MQTT_USERNAME                   \"{MQTT_USERNAME}\"",
        f"#define MQTT_USER_PASSWORD              \"{MQTT_USER_PASSWORD}\"",
        "",
        f"#define MQTT_CERTIFICATE                \"{cert_define}\"",
        f"#define MQTT_KEY                        \"{key_define}\"",
        f"#define MQTT_CA_CERTIFICATE             \"{ca_define}\"",
        "",
        pem_to_c_buffer("ca_certificate", ca_cert_path),
        "",
        pem_to_c_buffer("client_certificate", client_cert_path),
        "",
        pem_to_c_buffer("client_key", client_key_path),
        "",
        "#endif /* MQTT_CERTIFICATE_TEMPLATE_H */",
        "",
    ]

    with open(header_path, "w", encoding="utf-8", newline="\n") as out_file:
        out_file.write("\n".join(header_content))

    print(f"{CYAN}MQTT C template: {PURPLE}{header_path}{NO_COLOR}")


# =====================================================
def generate_mosquitto_config(template_output_dir, label):
    ca_cert_name = f"ca_{label}.crt"
    server_cert_name = f"server_{label}.crt"
    server_key_name = f"server_{label}.key"
    header_comment = [
        "# Auto-generated by gen_mqtt_certificate.py",
    ]
    generated_files = []

    for security_level in ["0", "1_2", "3_4"]:
        mosquitto_conf_path = os.path.join(template_output_dir, f"mosquitto_{security_level}.conf")

        if security_level == "0":
            conf_content = header_comment + [
                "listener 1883",
                "allow_anonymous true",
                "",
            ]
        elif security_level == "1_2":
            conf_content = header_comment + [
                "listener 8883",
                f"cafile /etc/mosquitto/cert/{ca_cert_name}",
                f"certfile /etc/mosquitto/certs/{server_cert_name}",
                f"keyfile /etc/mosquitto/certs/{server_key_name}",
                "use_identity_as_username false",
                "require_certificate false",
                "allow_anonymous false",
                "password_file /etc/mosquitto/passwd",
                "tls_version tlsv1.2",
                "",
            ]
        else:  # security_level == "3_4"
            conf_content = header_comment + [
                "listener 8883",
                f"cafile /etc/mosquitto/cert/{ca_cert_name}",
                f"certfile /etc/mosquitto/certs/{server_cert_name}",
                f"keyfile /etc/mosquitto/certs/{server_key_name}",
                "use_identity_as_username false",
                "require_certificate true",
                "allow_anonymous false",
                "password_file /etc/mosquitto/passwd",
                "tls_version tlsv1.2",
                "",
            ]

        with open(mosquitto_conf_path, "w", encoding="utf-8", newline="\n") as out_file:
            out_file.write("\n".join(conf_content))

        print(f"{CYAN}Mosquitto config: {PURPLE}{mosquitto_conf_path}{NO_COLOR}")
        generated_files.append(mosquitto_conf_path)

    return generated_files


# =====================================================
def generate_mosquitto_passwd(template_output_dir, username, password, iterations=101):
    if ":" in username:
        print(f"{RED}Invalid MQTT username: ':' is not allowed.{NO_COLOR}")
        sys.exit(0)

    salt = secrets.token_bytes(12)
    digest = hashlib.pbkdf2_hmac("sha512", password.encode("utf-8"), salt, iterations)
    salt_b64 = base64.b64encode(salt).decode("ascii")
    digest_b64 = base64.b64encode(digest).decode("ascii")

    passwd_path = os.path.join(template_output_dir, "passwd")
    with open(passwd_path, "w", encoding="utf-8", newline="\n") as out_file:
        out_file.write(f"{username}:$7${iterations}${salt_b64}${digest_b64}\n")

    print(f"{CYAN}Mosquitto passwd:{PURPLE} {passwd_path}{NO_COLOR}")
    return passwd_path


# =====================================================
def generate_archive(archive_path, certificate_paths, mosquitto_paths, passwd_path=None):
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for cert_path in certificate_paths:
            if os.path.exists(cert_path):
                archive.write(cert_path, arcname=os.path.join("certs", os.path.basename(cert_path)))

        for conf_path in mosquitto_paths:
            if os.path.exists(conf_path):
                archive.write(conf_path, arcname=os.path.join("conf.d", os.path.basename(conf_path)))

        if passwd_path and os.path.exists(passwd_path):
            archive.write(passwd_path, arcname=os.path.basename(passwd_path))

    print(f"{CYAN}Archive:         {PURPLE}{archive_path}{NO_COLOR}")


# =====================================================
# Main method
# =====================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate MQTT certificates")
    parser.add_argument("--label", type=str, default=USER_LABEL, help="User label for certificate generation")
    parser.add_argument("--cert", type=str, choices=["all", "ca", "client", "server"], default="all", help="Type of certificate to generate")
    parser.add_argument("--nokey", action="store_true", help="Do not renew key files for certificates")
    parser.add_argument("--output", type=str, help="Output directory for generated certificates")
    parser.add_argument("--header-output", type=str, help="Output directory for generated header file")
    parser.add_argument("--mqtt-username", type=str, default=MQTT_USERNAME, help="MQTT username for Mosquitto passwd file")
    parser.add_argument("--mqtt-password", type=str, default=MQTT_USER_PASSWORD, help="MQTT password for Mosquitto passwd file")
    args = parser.parse_args()

    MQTT_USERNAME = args.mqtt_username
    MQTT_USER_PASSWORD = args.mqtt_password

    script_dir = os.path.dirname(os.path.realpath(__file__))

    if not args.output:
        args.output = os.path.join(script_dir, "Certificates", "lfs")

    if not os.path.exists(args.output):
        os.makedirs(args.output)

    USER_LABEL = args.label
    CA_KEY = os.path.join(args.output, f"ca_{USER_LABEL}.key")
    CA_CERT = os.path.join(args.output, f"ca_{USER_LABEL}.crt")
    ca_config_path = os.path.join(script_dir, "mqtt", "ca_config.cnf")
    server_config_path = os.path.join(script_dir, "mqtt", "server_config.cnf")

    if not args.header_output:
        args.header_output = os.path.join(script_dir, "output")

    template_output_dir = args.header_output
    if not os.path.exists(template_output_dir):
        os.makedirs(template_output_dir)

    if args.cert in ["all", "ca"]:
        if not args.nokey or not os.path.exists(CA_KEY):
            run_openssl(f"openssl req -x509 -nodes -newkey rsa:4096 -keyout {CA_KEY} -days 11000 -out {CA_CERT} -config {ca_config_path} -extensions v3_req")
        else:
            run_openssl(f"openssl req -x509 -nodes -new -key {CA_KEY} -days 11000 -out {CA_CERT} -config {ca_config_path} -extensions v3_req")
        print(f"{CYAN}CA Certificate:     {PURPLE}{CA_CERT}{NO_COLOR}")
        display_cert(CA_CERT)
        print(f"{CYAN}CA Private Key:    {PURPLE}{CA_KEY}{NO_COLOR}")

    for cert_name in ["client", "server"]:
        if not os.path.exists(CA_KEY) or not os.path.exists(CA_CERT):
            print(f"{RED}CA key and certificate must be generated before generating {cert_name} certificate.{NO_COLOR}")
            sys.exit(0)

        if args.cert in ["all", cert_name]:
            print(f"{CYAN}Certificate for {cert_name}:{NO_COLOR}")
            key_path = os.path.join(args.output, f"{cert_name}_{USER_LABEL}.key")
            csr_path = os.path.join(args.output, f"{cert_name}_{USER_LABEL}.csr")
            config_path = os.path.join(script_dir, "mqtt", f"{cert_name}_config.cnf")

            if not args.nokey or not os.path.exists(key_path) or not os.path.exists(csr_path):
                run_openssl(f"openssl req -nodes -newkey rsa:2048 -keyout {key_path} -out {csr_path} -config {config_path}")

            # Generate certificate signed by CA
            cert_path = os.path.join(args.output, f"{cert_name}_{USER_LABEL}.crt")
            run_openssl(f"openssl x509 -req -in {csr_path} -CA {CA_CERT} -CAkey {CA_KEY} -CAcreateserial -out {cert_path} -days 11000")
            print(f"{CYAN}{cert_name.capitalize()} Certificate: {PURPLE}{cert_path}{NO_COLOR}")
            display_cert(cert_path)
            print(f"{CYAN}{cert_name.capitalize()} Private Key:  {PURPLE}{key_path}{NO_COLOR}")

    client_cert_path = os.path.join(args.output, f"client_{USER_LABEL}.crt")
    client_key_path = os.path.join(args.output, f"client_{USER_LABEL}.key")
    generated_sni = load_common_name(server_config_path)

    generate_header_template(
        template_output_dir,
        USER_LABEL,
        generated_sni,
        CA_CERT,
        client_cert_path,
        client_key_path,
    )

    generated_mosquitto_paths = generate_mosquitto_config(template_output_dir, USER_LABEL)
    passwd_path = generate_mosquitto_passwd(template_output_dir, MQTT_USERNAME, MQTT_USER_PASSWORD)

    certificate_paths = [
        os.path.join(args.output, f"ca_{USER_LABEL}.crt"),
        os.path.join(args.output, f"ca_{USER_LABEL}.key"),
        os.path.join(args.output, f"client_{USER_LABEL}.crt"),
        os.path.join(args.output, f"client_{USER_LABEL}.key"),
        os.path.join(args.output, f"server_{USER_LABEL}.crt"),
        os.path.join(args.output, f"server_{USER_LABEL}.key"),
    ]

    archive_path = os.path.join(template_output_dir, f"mqtt_artifacts_{USER_LABEL}.zip")
    generate_archive(archive_path, certificate_paths, generated_mosquitto_paths, passwd_path)
